### ISSUE TITLE
Option vs Result

### ISSUE THREAD

**Issue by ujh** [johnshaw/magnetic#1]
First of all I'm really happy that I've found this crate. This is exactly what I was looking for earlier today. :+1: 

Now on to my question: Why are you using [Option](https://doc.rust-lang.org/std/option/index.html) instead of [Result](https://doc.rust-lang.org/std/result/enum.Result.html)? The Result type seems to be the accepted rust type to use for handling errors (see for example [try_recv](https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.try_recv)).

**Comment by johnshaw** [comment]
Thanks. I wrote this mostly to learn Rust, so I'm glad you find it useful.

I considered using Result, but eventually settled on Option because I don't consider a failure to pop or push an error for the try_\* methods. I suspect I could be convinced otherwise.

**Comment by ujh** [comment]
I haven't used it yet, so I may curse you later today. :stuck_out_tongue_winking_eye:

And the difference between `Option` and `Result` are rather minimal. The only advantage to `Result` I can see is that it enables you to use stuff like the [try!](https://doc.rust-lang.org/std/macro.try!.html) macro. But I'm also not too knowledgable about Rust to know exactly what the best approach is.

**Comment by johnshaw** [comment]
Version 2.0 now returns result.
