### ISSUE TITLE
Communicate no remaining producers or consumers

### ISSUE THREAD

**Issue by teburd** [johnshaw/magnetic#5]
Seemingly right now the way this is written if all of the Producers disappear, the consumers will never know and be waiting forever. Vice versa, if all the Consumers disappear the producers will never know.

It would be nice if given the above situations that an Error is returned on receive() or send()

**Comment by johnshaw** [comment]
I considered this, but I didn't want to sacrifice any performance for this feature. The most common case where this would occur is usually a thread panic. I never catch panic in my own use cases so I haven't given this much thought, but I'm open to suggestions here. Would have to switch from `Option` to `Result` first #1 / [result](/johnshaw/magnetic/tree/result)
